#!/usr/bin/env python3
"""Download the fonts into `src/frontstep/static/fonts/` and regenerate `src/frontstep/static/fonts.css`.

Run by hand, not at build time: fonts change once in a blue moon, and a network
dependency inside a build is exactly the thing being escaped here.

    python3 scripts/fetch_fonts.py

Why self-hosted: the page has to hold up with no network. Fonts used to come
from fonts.googleapis.com and icons from a CDN, and offline the page lost every
font and every icon at once. Zero CDN, and no third-party request from a page
that runs locally.

Only the `latin` and `latin-ext` subsets: Cyrillic, Greek and Vietnamese would
be half a megabyte for characters nobody types here.
"""
import re
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# The package's static folder, which is where the app reads them from.
STATIC = REPO_ROOT / "src" / "frontstep" / "static"
FONTS = STATIC / "fonts"
UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"}

# IBM Plex in three registers: Sans for text, Sans Condensed for titles (one
# family in two cuts, instead of a second family to justify), Mono for paths,
# dates and numbers.
CSS_GOOGLE = (
    "https://fonts.googleapis.com/css2"
    "?family=IBM+Plex+Mono:wght@400;500"
    "&family=IBM+Plex+Sans+Condensed:wght@600;700"
    "&family=IBM+Plex+Sans:wght@400;500;600"
    "&display=swap"
)
SUBSETS = ("latin", "latin-ext")


def download(url: str) -> bytes:
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read()


def main() -> int:
    FONTS.mkdir(parents=True, exist_ok=True)
    css = download(CSS_GOOGLE).decode("utf-8")

    blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css)
    out, kept = [], []
    for subset, block in blocks:
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r"font-weight: (\d+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        name = f"{family.replace(' ', '')}-{weight}-{subset}.woff2"
        (FONTS / name).write_bytes(download(url))
        kept.append((family, weight, subset, (FONTS / name).stat().st_size))
        out.append(block.replace(url, f"fonts/{name}")
                        .replace("@font-face {", "@font-face {\n  font-display: swap;"))

    (STATIC / "fonts.css").write_text(
        "/* IBM Plex, self-hosted: no CDN. Generated by scripts/fetch_fonts.py,\n"
        "   not edited by hand. latin and latin-ext only. */\n\n"
        + "\n\n".join(out) + "\n", encoding="utf-8")

    for family, weight, subset, size in kept:
        print(f"  {family:26} {weight}  {subset:9}  {size // 1024:3} KB")
    print(f"\n{len(kept)} files, {sum(k[3] for k in kept) // 1024} KB")
    print("Font Awesome lives in src/frontstep/static/fontawesome.css + src/frontstep/static/fonts/fa-*.woff2,")
    print("downloaded once from 5.15.4: it does not need regenerating.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
