# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Giovanni J. Costantini
"""Reading the open fronts: scans the status documents of every project.

Nothing is persisted: the filesystem is read again on every request. These are a
few dozen files and a single page, so a cache would only be a way of showing
stale data.

The parser is deliberately tolerant: a status document without a header is not
an error, it is a project whose header still has to be written.

There is MORE THAN ONE root — the folders where someone keeps their projects —
and a project's name is unique within its root, not across roots: the root is
part of every project's address.
"""
from __future__ import annotations

import configparser
import datetime as dt
import hashlib
import math
import ntpath
import os
import posixpath
import re
import stat
import tempfile
import zlib
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import quote

from . import __version__

# Two different folders, not to be confused: templates and static files live in
# the PACKAGE, while the `.git` the signature reads the commit from lives in the
# REPO ROOT. When Frontstep is installed as a package the second one is not a git
# repository at all, and the signature still holds with an empty commit.
PACKAGE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_DIR.parents[1]

# The version lives in __init__.py and nowhere else: the page, /health and
# pyproject.toml (hatchling) all read it from that one line.
VERSION = __version__

# The repository name is declared rather than derived from the folder: inside a
# container the code sits in /app and the signature would say "app".
REPO_NAME = "frontstep"

# ---- attribution -----------------------------------------------------------
#
# The mark at the foot of the page. It is not decoration and it is not a
# copyright line either — it is the attribution NOTICE asks for, put where such
# notices normally appear in this product.
#
# ⚠️ Removing it from a distributed derivative is not a style choice: section
# 4(d) of the Apache License requires the contents of NOTICE to be carried in at
# least one of three places, and for a single-page application the foot of the
# page IS the third of them ("within a display generated by the Derivative
# Works, if and wherever such third-party notices normally appear"). NOTICE
# names this line explicitly for that reason.
#
# A fork changes the product name; it does not drop this. See NOTICE and
# TRADEMARK.md for what a fork's footer has to say instead.
AUTHOR = "G.J.C."
AUTHOR_MARK = "🧠"
# Where the mark links to. If it is ever emptied the signature falls back to
# plain text rather than a dead link — the attribution does not depend on the
# link existing.
PROJECT_URL = "https://github.com/GiovanniCst/frontstep"

# ---- statuses --------------------------------------------------------------
#
# Canonical in ENGLISH, because that is the language of the project. A document
# may well declare them in another language, and then writing puts back the
# language that document already uses: the file belongs to whoever wrote it, and
# must not change language under their hands just because a dashboard passed by.
ACTIVE = "active"
WAITING = "waiting"
PAUSED = "paused"
DONE = "done"
# Not a status of the work but a diagnosis of the document: its header declares
# nothing. This is never written to a file, only shown.
UNDECLARED = "undeclared"

# Reading order of the page: first what can be acted on right now.
STATUS_ORDER = [ACTIVE, WAITING, PAUSED, UNDECLARED, DONE]

# How each status is spelled in each supported language. This table is what lets
# an Italian document stay Italian after a "Close".
STATUS_BY_LANGUAGE = {
    ACTIVE:  {"en": "active",  "it": "attivo"},
    WAITING: {"en": "waiting", "it": "in-attesa"},
    PAUSED:  {"en": "paused",  "it": "sospeso"},
    DONE:    {"en": "done",    "it": "concluso"},
}

LABELS = {
    ACTIVE: "Active",
    WAITING: "Waiting on others",
    PAUSED: "Paused",
    UNDECLARED: "Header to fix",
    DONE: "Done",
}

# The SECTIONS of the page: three, and they are also the three filters, under
# the same names. A card belongs to exactly one section and the filter that
# hides it is named after that section — there is no mapping to keep in mind
# between what you tick and what disappears.
#
# Three statuses end up under "Open", and none of them deserves a section of
# its own:
#   - `waiting`: a project blocked on someone else is still an open project, and
#     pushing it behind every active one breaks the only reading that matters —
#     most recent to most silent. You recognise it by the amber dot and by the
#     "waiting for" box on the card;
#   - `undeclared`: that is a diagnosis of the header, not a status of the work.
#     The project is open all the same, and the card says so with a badge.
# The colour of a section's dot is the colour of the first status in it.
SECTIONS = [
    ("open", "Open", (ACTIVE, WAITING, UNDECLARED)),
    ("paused", "Paused", (PAUSED,)),
    ("closed", "Closed", (DONE,)),
]

# status -> index of its section. This is what sorts the page, not the status:
# inside "Open", active and waiting weigh the same and recency decides.
_SECTION_OF_STATUS = {s: i for i, (_, _, statuses) in enumerate(SECTIONS) for s in statuses}

# The statuses of the first section. Taken from SECTIONS rather than written out
# again: if "Open" ever changes composition, the silence line follows by itself.
OPEN_STATUSES = SECTIONS[0][2]

# Synonyms accepted when reading, in both languages, so that a hand-written
# header does not fall into "undeclared" over a hyphen.
# The plurals serve the section titles of an external index ("Projects — paused").
STATUS_ALIASES = {
    "active": ACTIVE, "ongoing": ACTIVE, "in progress": ACTIVE,
    "attivo": ACTIVE, "attiva": ACTIVE, "attivi": ACTIVE, "in corso": ACTIVE,

    "waiting": WAITING, "blocked": WAITING, "on hold": WAITING,
    "in-attesa": WAITING, "in attesa": WAITING, "inattesa": WAITING, "attesa": WAITING,

    "paused": PAUSED, "suspended": PAUSED, "shelved": PAUSED,
    "sospeso": PAUSED, "sospesa": PAUSED, "sospesi": PAUSED,

    "done": DONE, "completed": DONE, "closed": DONE, "shipped": DONE,
    "concluso": DONE, "conclusa": DONE, "conclusi": DONE, "chiuso": DONE,
}

# ---- the header fields -----------------------------------------------------
#
# The convention IS the product, so it has to exist in more than one language:
# nobody writing in English will ever type `**Prossimo passo:**`, and documents
# already written in Italian have to keep working without migrating a single one.
#
# For each field: the canonical name per language (the one that gets WRITTEN)
# and the aliases tolerated on reading only.
FIELDS = {
    "status":      {"en": "Status",      "it": "Stato",          "alias": ("State",)},
    "updated":     {"en": "Updated",     "it": "Aggiornato",     "alias": ("Last updated", "Date")},
    "next_step":   {"en": "Next step",   "it": "Prossimo passo", "alias": ("Next",)},
    "waiting_for": {"en": "Waiting for", "it": "In attesa di",   "alias": ("Waiting on", "Blocked by")},
    "app":         {"en": "App",         "it": "App",            "alias": ("Nome app", "Nome", "Product")},
    "description": {"en": "Description", "it": "Descrizione",    "alias": ("About",)},
    "tags":        {"en": "Tags",        "it": "Tag",            "alias": ("Etichette", "Labels",
                                                                          "Domain", "Dominio", "Ambito")},
    "prod":        {"en": "Prod",        "it": "Prod",           "alias": ("Production", "Produzione",
                                                                          "Deploy", "Deployed")},
}

LANGUAGES = ("en", "it")


def field_names(field: str) -> tuple[str, ...]:
    """Every name under which that field may appear in a document."""
    entry = FIELDS[field]
    return tuple(dict.fromkeys([entry["en"], entry["it"], *entry["alias"]]))


def field_name(field: str, language: str = "en") -> str:
    """The name that field is WRITTEN with, in the given language."""
    return FIELDS[field][language if language in LANGUAGES else "en"]


# The tag meaning "this one is running in production". It is not a tag like the
# others only because it has a field of its own in the header (`Prod:`), whose
# value — the name of the service or container — is kept as the badge's note.
PROD_TAG = "prod"

# Why `Prod` is DECLARED and not measured: a tag that depended on being able to
# reach the infrastructure would disappear every time the page is opened from
# another network, which is the opposite of what it is for.
#
# A field filled in with a negation is not a declaration of production:
# "no", "not yet", "never" count as an absent field.
PROD_NEGATIONS = ("no", "not yet", "none", "never", "-", "n/a",
                  "non ancora", "nessuno", "mai")

CANONICAL_NAME = "CURRENT_STATUS.md"
RE_FIELD = r"^\s*\*\*{field}:?\*\*:?\s*(.*?)\s*$"
RE_DATE = re.compile(r"(\d{4})-(\d{2})-(\d{2})")
# A line of the optional external index: "- **active** — [Title](file.md) — text"
RE_INDEX_LINE = re.compile(
    r"^-\s+\*\*(?P<status>[^*]+)\*\*\s*[—-]\s*\[(?P<title>[^\]]+)\]\((?P<file>[^)]+)\)\s*[—-]?\s*(?P<desc>.*)$"
)
# A project referenced inside an index line: a path in backticks, whose LAST
# segment names the project — a folder (`~/code/tracker/`), or a single file for
# a project that lives in a document rather than a folder of its own.
# ⚠️ Any prefix. It used to require `~/projects/`, so an index written by anyone
# who keeps their projects elsewhere matched nothing, silently.
RE_REFERENCE = re.compile(r"`\s*([^`]*?/[^`/]+)/?\s*`")
RE_EXTENSION = re.compile(r"\.[a-z0-9]{1,5}$", re.IGNORECASE)


@dataclass(frozen=True)
class Root:
    """A folder that projects are scanned from.

    It is not just one more path: a project's name is unique within its root and
    not across roots, so the root is part of every project's address
    (`/project/<root>/<name>`). Two folders with the same name under two roots
    are two different projects, and "Close" has to write to the right file.

    It also carries the base TAGS of its projects: where a project sits says
    what kind of work it is, and the project's own document can add to that.
    """
    key: str        # in the URL and in the element ids on the page
    folder: str     # where projects are scanned from (inside the container, if any)
    host: str       # the same path on the host: this is what gets copied
    prefix: str     # how it reads on a card: "~/projects/" or "~/"
    label: str = ""             # what this folder is called, for whoever uses it
    tags: tuple[str, ...] = ()  # base tags, inherited by every project under it

    def __post_init__(self):
        if not self.label:
            object.__setattr__(self, "label", self.key)


@dataclass
class Project:
    name: str
    status: str
    title: str = ""
    description: str = ""         # from the Description field, or derived from the text
    description_derived: bool = False
    folder: str = ""              # folder name inside the root, "" if it has none
    root: str = ""                # key of the root it was found under
    prefix: str = ""              # the path as it reads on the card
    host_folder: str = ""         # the folder on the host, for the path tooltip
    # The tags: the root's plus the document's. The FIRST one is what the card
    # shows as a coloured band; the others are badges in the footer.
    tags: tuple[str, ...] = ()
    app_name: str = ""            # what the product is called, from the App field
    in_production: bool = False   # the Prod field is there and is not a negation
    prod_note: str = ""           # its value: usually the name of the service
    updated: dt.date | None = None
    next_step: str = ""
    waiting_for: str = ""
    status_file: str = ""         # HOST path, the one that gets copied
    status_filename: str = ""     # the file name as found on disk
    mtime: dt.date | None = None
    remote_url: str = ""          # the repository's origin remote, if it has one
    has_status_file: bool = False
    has_header: bool = False
    has_status: bool = False      # there is a status line that can be rewritten
    has_next_step: bool = False   # there is a next step line that can be rewritten
    canonical_casing: bool = True
    index_note: str = ""
    index_file: str = ""

    @property
    def status_label(self) -> str:
        """The status as a word to read, in English, ready for `t()`.

        Not the canonical value: `active` is what the document and the URL say,
        and it is a token, not a word anybody should be read out. The card shows
        the status as the colour of its paper, so the only place this surfaces is
        the line a screen reader gets — and that line used to announce "active"
        in the middle of a page otherwise entirely in Italian, because the raw
        status went straight into the markup.
        """
        return LABELS.get(self.status, self.status)

    @property
    def days_silent(self) -> int | None:
        """How many days this project has not moved.

        The `Updated` field is the declared date of the last real work and beats
        the mtime, which changes for a typo fix too.
        """
        reference = self.updated or self.mtime
        if reference is None:
            return None
        return (dt.date.today() - reference).days

    @property
    def header_behind(self) -> bool:
        """The file was touched after the date its header declares."""
        if not (self.updated and self.mtime):
            return False
        return (self.mtime - self.updated).days > 1

    @property
    def section_index(self) -> int:
        """Index of the section the card lands in, not of the status."""
        return _SECTION_OF_STATUS.get(self.status, len(SECTIONS))

    @property
    def ident(self) -> str:
        """Unique key on the page: the name alone is no longer enough.

        Two roots can hold two folders with the same name, and two equal ids
        would break the silence line — it would scroll to the wrong card —
        without telling anyone why.
        """
        return f"{self.root}:{self.name}" if self.root else self.name


def _normalize_status(raw: str) -> str:
    """Canonical status from a hand-written value. "" if not recognised.

    It copes with the qualifications an external index drags along:
    "paused 2026-04-23" → paused, "active, to run" → active.
    """
    text = (raw or "").strip().lower()
    if not text:
        return ""
    if text in STATUS_ALIASES:
        return STATUS_ALIASES[text]
    words = [w for w in re.split(r"[\s,;]+", text) if w]
    for n in (2, 1):                      # "on hold" before "on"
        candidate = " ".join(words[:n])
        if candidate in STATUS_ALIASES:
            return STATUS_ALIASES[candidate]
    return ""


def _field_regex(name: str) -> re.Pattern:
    return re.compile(RE_FIELD.format(field=re.escape(name)), re.IGNORECASE)


def _find_field(lines: list[str], field: str) -> tuple[int, str, str] | None:
    """(line number, name used, value) of the field's first occurrence, in any
    of the languages and aliases. None if it is not there.

    The FIRST one wins: long documents repeat "Updated" in the body, and that is
    not the header. Lines are scanned outer and names inner, otherwise an alias
    quoted at the bottom of a document would beat the real field written on top.

    ⚠️ Fenced blocks are skipped. A document that SHOWS the header format in a
    ``` block before writing its own had the example matched instead of the
    header — read from it, and written into it.
    """
    patterns = [(name, _field_regex(name)) for name in field_names(field)]
    inside_fence = False
    for i, line in enumerate(lines):
        if line.lstrip().startswith(("```", "~~~")):
            inside_fence = not inside_fence
            continue
        if inside_fence:
            continue
        for name, rx in patterns:
            m = rx.match(line)
            if m:
                return i, name, m.group(1).strip()
    return None


def _read_field(lines: list[str], field: str) -> str:
    """The field's value in the header, in whatever language it is written."""
    found = _find_field(lines, field)
    return found[2] if found else ""


def _has_field(lines: list[str], field: str) -> bool:
    """The field's LINE is there, even with an empty value.

    Not the same question as `_read_field(...) != ""`: a `**Status:**` with no
    value is a line that can be rewritten, and whether the "Close" button has
    anything to work on depends on it.
    """
    return _find_field(lines, field) is not None


def normalize_tag(raw: str) -> str:
    """A hand-written tag becomes a stable key: `Prod`, `prod` and `PROD` are
    the same tag. Without this, the same word spelled two ways would become two
    different filters on the page."""
    text = (raw or "").strip().strip("`*").lower()
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"[^a-z0-9àáâäãåèéêëìíîïòóôöõùúûüñç.-]", "", text)
    return text.strip("-.")


# The historical names of the field that carries tags today. When a value comes
# from one of these it was an ENUM of a few entries, not a free tag: `PERSONALE`
# and `personal` were the same domain, and letting them become two different
# tags would be a regression for documents already written. The aliases apply
# HERE ONLY: whoever writes `Tags: personale` today means that tag, and keeps it.
LEGACY_DOMAIN_FIELDS = ("Domain", "Dominio", "Ambito")

LEGACY_TAG_ALIASES = {
    "personale": "personal", "privato": "personal", "private": "personal",
    "casa": "personal", "home": "personal",
    "lavoro": "work", "azienda": "work", "company": "work", "ufficio": "work",
}


def project_tags(lines: list[str], from_root: tuple[str, ...],
                 in_production: bool = False) -> tuple[str, ...]:
    """A project's tags: its root's, plus its document's own.

    Two levels, because they answer two different questions: the root says what
    that folder is (`work`), the document says what that project is (`prod`,
    `client-acme`). "In production" is a property of the single project, not of
    the folder holding it, and with one exclusive domain it was not expressible.

    An inherited tag can be REMOVED by writing it with a minus: `-work`. That
    serves the rare but real case of a project sitting in the wrong folder — a
    personal one among the work ones — and without it inheritance would be a cage.

    Order matters: the first tag is the one the card shows as its band, and it
    stays the root's until someone takes it away.
    """
    added: list[str] = []
    removed: set[str] = set()
    found = _find_field(lines, "tags")
    raw = found[2] if found else ""
    legacy = bool(found) and found[1] in LEGACY_DOMAIN_FIELDS

    def tag(piece: str) -> str:
        key = normalize_tag(piece)
        return LEGACY_TAG_ALIASES.get(key, key) if legacy else key

    for piece in re.split(r"[,;]", raw):
        piece = piece.strip()
        if not piece:
            continue
        if piece.startswith("-"):
            removed.add(tag(piece[1:]))
        else:
            added.append(tag(piece))
    if in_production:
        added.append(PROD_TAG)

    ordered = [t for t in from_root if t and t not in removed]
    ordered += [t for t in added if t and t not in removed]
    return tuple(dict.fromkeys(ordered))


def document_language(lines: list[str]) -> str:
    """Which language the header is written in: "it" or "en".

    This is needed when WRITING: a document that says `**Stato:** attivo` has to
    stay that way after a "Close", not turn into `**Status:** done`. It looks at
    how the field NAMES are written, not the values: the name is a choice made
    by whoever wrote the file, the value may have been put there by someone else.

    On a tie (or with no recognisable field) English wins, being the project's
    canonical language. Fields spelled the same in both languages — `App`,
    `Prod` — do not vote, and rightly so: they say nothing about the language.
    """
    votes = {"en": 0, "it": 0}
    for field, entry in FIELDS.items():
        if entry["en"].lower() == entry["it"].lower():
            continue
        found = _find_field(lines, field)
        if found is None:
            continue
        name = found[1].lower()
        for language in LANGUAGES:
            if name == entry[language].lower():
                votes[language] += 1
    return "it" if votes["it"] > votes["en"] else "en"


def _parse_date(text: str) -> dt.date | None:
    m = RE_DATE.search(text or "")
    if not m:
        return None
    try:
        return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


def _find_status_file(folder: Path) -> Path | None:
    """The right casing is CURRENT_STATUS.md, but variants are read all the same."""
    exact = folder / CANONICAL_NAME
    if exact.is_file():
        return exact
    try:
        for entry in sorted(folder.iterdir()):
            if entry.is_file() and entry.name.lower() == CANONICAL_NAME.lower():
                return entry
    except OSError:
        pass
    return None


def document(name: str, root_path: str, host_root: str) -> dict | None:
    """A project's status document, read again right now. None if there is none.

    `name` comes from the URL, so it is a label and not a path: it has to
    resolve to a DIRECT CHILD folder of root_path. That is checked after
    resolve(), not on the string, so a symlink pointing outside falls too.
    """
    if not name or "/" in name or "\\" in name or name.startswith("."):
        return None
    root = Path(root_path).resolve()
    try:
        folder = (root / name).resolve()
    except OSError:
        return None
    if folder.parent != root or not folder.is_dir():
        return None

    path = _find_status_file(folder)
    if path is None:
        return None
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
        mtime = dt.datetime.fromtimestamp(path.stat().st_mtime)
    except OSError:
        return None
    return {
        "name": folder.name,
        "text": text,
        "file": path.name,
        "host_path": host_join(host_root, folder.name, path.name),
        "mtime": mtime,
        "lines": text.count("\n") + 1,
    }


def host_join(base: str, *parts: str) -> str:
    """Join a path in the shape of the BASE, not of this machine.

    ⚠️ Not `os.path.join` and not `Path`: both answer for the machine running
    the code, and in a container the host path belongs to somebody else's — it
    may be Windows while this runs on Linux. Both joins already handle a base
    ending in a separator, `/` included.
    """
    flavour = ntpath if ntpath.splitdrive(base)[0] or "\\" in base else posixpath
    return flavour.join(base, *parts)


# A folder name accepted for a new project. Accented letters are genuinely
# needed: real project folders have them. Out: `/`, `\`, spaces, `..`, and the
# leading dot (dot-folders are never scanned, so they are never created either).
RE_NEW_NAME = re.compile(r"^[A-Za-z0-9\u00C0-\u024F][A-Za-z0-9\u00C0-\u024F._-]{0,63}$")


# The markers around our section of an AGENTS.md. They exist so that installing
# it twice replaces one section instead of stacking two, and so that everything
# outside them is somebody else's file and stays untouched.
AGENTS_FILE = "AGENTS.md"
AGENTS_MARKERS = ("<!-- frontstep:begin -->", "<!-- frontstep:end -->")

# Where an Agent Skill goes for Claude Code. The FOLDER is the question that
# matters: `~/.claude` existing is how this machine says it has Claude Code on
# it, and nothing offers to install anything when it does not — creating another
# program's configuration directory on a machine that does not use it is not
# ours to do.
CLAUDE_HOME = ".claude"
SKILL_FILE = "SKILL.md"


def claude_skill_path(home: Path | None = None) -> Path:
    """Where the skill goes. Not a promise that anything is there."""
    return (home or Path.home()) / CLAUDE_HOME / "skills" / "frontstep" / SKILL_FILE


def claude_is_here(home: Path | None = None) -> bool:
    """Whether this machine looks like it runs Claude Code."""
    return ((home or Path.home()) / CLAUDE_HOME).is_dir()


def install_claude_skill(home: Path | None = None) -> Path:
    """Write the skill where Claude Code reads its skills from. Returns the path.

    One file, overwritten if it is already there — unlike `AGENTS.md`, this path
    is ours by name and holds nothing anybody else wrote.
    """
    target = claude_skill_path(home)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text((PACKAGE_DIR / "assets" / SKILL_FILE).read_text(encoding="utf-8"),
                      encoding="utf-8")
    return target


def write_agents_block(folder: str | Path) -> tuple[Path, str]:
    """Put the Frontstep section into `folder`'s AGENTS.md. Returns (path, what).

    `what` is "created", "replaced" or "appended" — a caller has to be able to
    say which, because appending to a file somebody else wrote is a different
    event from creating one.

    ⚠️ It lives here and not in the CLI because there are now TWO ways in: the
    command, and the checkbox on "New project". The same lesson as
    `create_example`, which was called by `init` and not by the page that had
    become the main way in — one copy of a behaviour is the only way the two
    cannot drift.
    """
    target = Path(folder).expanduser() / AGENTS_FILE
    block = (PACKAGE_DIR / "assets" / AGENTS_FILE).read_text(encoding="utf-8")
    start, end = AGENTS_MARKERS

    if not target.exists():
        target.write_text(block, encoding="utf-8")
        return target, "created"

    existing = target.read_text(encoding="utf-8")
    if start in existing and end in existing:
        head = existing.split(start)[0]
        tail = existing.split(end, 1)[1]
        target.write_text(head + block.strip() + tail, encoding="utf-8")
        return target, "replaced"

    target.write_text(existing.rstrip() + "\n\n" + block, encoding="utf-8")
    return target, "appended"


def create_project(name: str, root: Root, description: str, app_name: str = "",
                   today: dt.date | None = None, language: str = "en",
                   require_description: bool = True,
                   with_agents: bool = False) -> dict | None:
    """Create a new project's folder and its status document.

    ⚠️ This is one of the few places where Frontstep writes inside someone
    else's project, so the perimeter is kept tight right here:

      - the root never arrives from the client: it is one of the roots declared
        in the configuration, picked by key;
      - the name goes through `RE_NEW_NAME` and then through the same check as
        `document()` — a direct child of the root, verified AFTER resolve(), so
        a symlink pointing outside falls too;
      - if a status document is already there it refuses: that document belongs
        to whoever wrote it;
      - if writing fails, a folder we just created is removed, so that half a
        project is not left behind.

    `with_agents` also drops an `AGENTS.md` in there — the instructions that
    make the agent keep the document current. It is asked for by a checkbox and
    never assumed: the folder may be one that already existed, and that file is
    read by every agent that opens the project, not only by ours.

    Returns {"name", "root", "file"} or a dict carrying `error`.
    """
    def failed(why: str) -> dict:
        return {"error": why}

    if not name or not RE_NEW_NAME.match(name):
        return failed(
            "Name not allowed: letters, digits, dot, dash and underscore, "
            "64 characters at most, and it cannot start with a dot.")
    if ".." in name:
        return failed("Name not allowed.")

    # Line breaks always go: the parser reads the field with a single-line
    # regex, and a break inside the value would cut the description short.
    description = " ".join((description or "").split())
    if not description and require_description:
        # Asked for when a person is creating a project and can answer. Adopting
        # a folder in bulk is the other case: there the description is derived
        # from the README, and where there is nothing to derive an empty field
        # is honest — the card says "no description" instead of showing one that
        # was made up.
        return failed("A description is needed: without one the card is born mute.")
    if len(description) > 140:
        # The maximum stays, and it is a measure of the layout: past that, the
        # description does not fit a card and gets truncated by whoever reads
        # it. There is no minimum — a brand new project does not always have
        # much to say yet.
        return failed(
            f"The description cannot go past 140 characters (this one has {len(description)}).")

    base = Path(root.folder).resolve()
    try:
        folder = (base / name).resolve()
    except OSError:
        return failed("Name not allowed.")
    if folder.parent != base:
        return failed("Name not allowed.")
    # The defence is NOT "the folder must not exist" but "the document must not
    # exist": a folder already there without a status document is the normal
    # case of a project born before the dashboard, or moved in from elsewhere.
    # There the document is added and nothing else is touched.
    adopting = folder.exists()
    if adopting:
        if not folder.is_dir():
            return failed(f"{name} exists and is not a folder.")
        if _find_status_file(folder) is not None:
            return failed(
                f"{root.prefix}{name} already has a status document: "
                "that one gets edited, not replaced by another.")

    # The header of a NEW document is written in the configured language: there
    # is no document to inherit it from, and this is the only time the language
    # is chosen by whoever runs Frontstep rather than by the file itself.
    def field(key: str, value: str = "") -> str:
        return f"**{field_name(key, language)}:** {value}".rstrip()

    lines = [
        f"# {app_name or name}",
        "",
        field("status", STATUS_BY_LANGUAGE[ACTIVE][language]),
        field("updated", (today or dt.date.today()).isoformat()),
        field("next_step"),
        field("waiting_for"),
    ]
    if app_name:
        lines.append(field("app", app_name))
    lines += [field("description", description), ""]
    text = "\n".join(lines)

    if not adopting:
        try:
            # no exist_ok: if the folder appeared between the check and now,
            # this must fail instead of writing into it.
            folder.mkdir()
        except OSError:
            return failed("Cannot create the folder.")

    path = folder / CANONICAL_NAME
    try:
        path.write_text(text, encoding="utf-8")
        # Same reason as set_status: in a container the process writes as root,
        # and a new project owned by root:root is not editable by its author.
        # Owner and group are copied from the FOLDER when adopting (it belongs
        # to whoever works there) and from the ROOT for a brand new one. Never
        # from whoever does the writing.
        before = (folder if adopting else base).stat()
        try:
            if not adopting:
                os.chown(folder, before.st_uid, before.st_gid)
            os.chown(path, before.st_uid, before.st_gid)
        except (PermissionError, AttributeError):
            pass
    except OSError:
        path.unlink(missing_ok=True)
        if not adopting:
            # A folder that was there before us is never removed, not even to
            # clean up after a failure of ours.
            try:
                folder.rmdir()
            except OSError:
                pass
        return failed("Cannot write the status document.")

    result = {"name": name, "root": root.key, "file": str(path),
              "adopted": adopting}

    # The agent instructions, when they were asked for. AFTER the project
    # exists, and never able to undo it: the project is the thing being created
    # and this is an extra on top, so a failure here is reported and not fatal.
    # Ownership is copied for the same reason as the document above.
    if with_agents:
        try:
            agents, what = write_agents_block(folder)
            try:
                os.chown(agents, before.st_uid, before.st_gid)
            except (PermissionError, AttributeError):
                pass
            result["agents"] = {"file": str(agents), "what": what}
        # ⚠️ `UnicodeDecodeError` too, which is a ValueError and not an OSError:
        # an existing `AGENTS.md` that is not UTF-8 raised straight out of here,
        # so the route answered 500 with the project already created — and this
        # branch, which exists to report exactly that, was never reached.
        except (OSError, ValueError) as e:
            result["agents_error"] = str(e)

    return result


# The folder a first run creates, so the dashboard never opens empty. Its status
# document IS the tutorial: the first thing anybody reads about the convention is
# an example of it, on their own machine, in the place it belongs.
EXAMPLE_FOLDER = "frontstep-example"


def create_example(root_path: str, today: dt.date | None = None,
                   language: str = "en") -> Path | None:
    """Create the example project inside `root_path`. None if it was already there.

    ⚠️ Here, and not in the CLI where it started, because there are TWO ways in
    now — `frontstep init` and the setup page — and only one of them called it.
    Measured on a clean Windows 11: setting Frontstep up in the browser produced
    a dashboard saying "No project matches these filters", which is exactly the
    empty page this folder exists to prevent. The rule the project holds itself
    to — a dashboard that opens empty looks broken — had been kept on one path
    and dropped on the one that had just become the main way in.

    Nothing of the user's is touched: the folder is ours, its name is ours, and
    if something is already there it is left exactly as it is.
    """
    example = Path(root_path).expanduser() / EXAMPLE_FOLDER
    if example.exists():
        return None
    # ⚠️ In the language that was CHOSEN. The example is the first thing anybody
    # reads about the convention, and its header is a worked instance of it — so
    # in Italian it has to say `**Stato:** attivo`, not `**Status:** active`.
    # It did not: there was one asset, in English, and picking Italian during
    # setup produced an English tutorial with an English header.
    asset = PACKAGE_DIR / "assets" / f"example_status.{language}.md"
    if not asset.is_file():
        asset = PACKAGE_DIR / "assets" / "example_status.md"
    template = asset.read_text(encoding="utf-8")
    try:
        example.mkdir(parents=True)
        (example / CANONICAL_NAME).write_text(
            template.format(today=(today or dt.date.today()).isoformat(),
                            root_path=str(Path(root_path).expanduser())),
            encoding="utf-8")
    except OSError:
        # A first run that cannot write its own example is not a first run that
        # should fail: the configuration is the thing that matters, and it has
        # already been written by the time this is called.
        return None
    return example


# Folders people keep projects in. Not a guess about any one machine — nothing
# is used unless it EXISTS, and what makes a suggestion worth offering is the
# count next to it, which is measured.
LIKELY_ROOTS = ("projects", "code", "dev", "src", "work", "repos", "git",
                "Projects", "Code", "Developer", "Documents")


def suggest_roots(home: Path | None = None) -> list[dict]:
    """Folders on this machine that could be roots, most promising first.

    So that a first run is a click rather than a path typed from memory — and
    typing a path from memory is how somebody ends up with a dashboard that is
    empty for a reason they cannot see.

    Each carries `projects`: how many of its immediate children already have a
    status document. That number is the whole point. It sorts the list, and it
    answers the question the form cannot ask — "is this the folder you meant?" —
    with a fact instead of a folder name.
    """
    home = home or Path.home()
    found: list[dict] = []
    seen: set[Path] = set()

    for name in ("",) + LIKELY_ROOTS:            # "" is the home folder itself
        path = home / name if name else home
        try:
            resolved = path.resolve()
        except OSError:
            continue
        if resolved in seen or not path.is_dir():
            continue
        seen.add(resolved)
        found.append({
            "path": str(path),
            # The home folder's own name is the USER NAME, and it would end up
            # on screen and in every screenshot. Same reason as `config.py`.
            "label": "Home" if path == home else path.name,
            "projects": _count_documented(path),
        })

    # Most documents first — a folder that already has status documents in it is
    # almost certainly the one being looked for.
    #
    # ⚠️ Then the HOME FOLDER LAST, and that tiebreak is the whole point on a
    # first run. Measured on a clean machine: every count is zero, because
    # nobody has adopted the convention yet, so the first key decides nothing
    # and whatever sorts first is what gets offered. The home folder has the
    # shortest path, so it won — and suggesting "scan your entire home
    # directory" as the opening move is not what somebody means by "where are
    # your projects".
    found.sort(key=lambda r: (-r["projects"], r["path"] == str(home), len(r["path"])))
    return found


def _count_documented(folder: Path, limit: int = 400) -> int:
    """How many immediate children of this folder have a status document.

    One level only, and capped: this runs while somebody waits for a page, and
    a home folder can hold a great many directories. Dot-folders are skipped
    because `scan` skips them too — counting what will never be shown would
    make the number a lie.
    """
    count = 0
    try:
        for i, child in enumerate(folder.iterdir()):
            if i >= limit:
                break
            if child.name.startswith(".") or not child.is_dir():
                continue
            if _find_status_file(child) is not None:
                count += 1
    except OSError:
        return 0
    return count


class WriteFailed(Exception):
    """The document was found and could be rewritten, and the write itself failed.

    Separate from returning None — which means "there is no such line to change"
    — because the two send whoever is reading in opposite directions: one says
    look at your header, the other says look at your disk.
    """


def _apply_to_header(name: str, root_path: str,
                     updates: Callable[[str], dict[str, str]],
                     required: tuple[str, ...] = ()) -> dict | None:
    """Rewrite named lines of a status document's header. None if it cannot be.

    EVERY write into somebody else's document goes through here — `set_status`
    and `set_next_step` — so that the defences are written once and cannot drift
    apart as more of them appear:

      * the project has to resolve to a DIRECT CHILD of the root; `document()`
        checks that after resolve(), so a symlink pointing outside falls too;
      * ONE line per field is rewritten, the FIRST one, the header's: the rest
        of the file goes back to disk character for character as it was;
      * the field NAME the document already uses is kept — whoever wrote `Last
        updated` does not see it turn into `Updated` for pressing a key;
      * the write is ATOMIC (temporary file in the same folder + rename), so a
        failure half-way does not leave a truncated status document behind;
      * owner and permissions are copied onto the temporary file BEFORE the
        rename, or in a container the document would come back owned by root
        and its author could no longer edit it;
      * a field listed in `required` whose line is NOT there makes the whole
        write refuse: no header gets invented on its author's behalf.

    `updates` is a function of the document's LANGUAGE, because what gets
    written can depend on it: a status is spelled `attivo` in an Italian file,
    and a document must not change language because a dashboard passed by.

    Returns {"name", "language", "written"} — `written` being the fields that
    actually found a line, which is not always all of them.
    """
    doc = document(name, root_path, root_path)
    if doc is None:
        return None

    path = Path(root_path).resolve() / doc["name"] / doc["file"]

    # ⚠️ Re-read the bytes rather than reuse `doc["text"]`: that was decoded with
    # `errors="replace"` for DISPLAY, and writing it back would put U+FFFD on
    # disk in place of every byte it could not read. A document that is not UTF-8
    # is left alone instead — the caller reports it, nothing is destroyed.
    try:
        text = path.read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    # The file's own line ending, kept: `read_text`/`write_text` would translate
    # every one of them and turn a one-line change into a whole-file diff.
    newline = "\r\n" if "\r\n" in text else "\n"
    lines = text.replace("\r\n", "\n").split("\n")

    # ⚠️ Writing happens in the DOCUMENT's language, not the project's: a file
    # saying `**Stato:** attivo` has to stay that way after a "Close". The
    # dashboard is only passing through; the document belongs to its author.
    language = document_language(lines[:40])
    values = updates(language)

    written: dict[str, str] = {}
    for field, value in values.items():
        # Only the head, the same window `read_project` reads: a field further
        # down is body text, and the card would not offer a button for it.
        found = _find_field(lines[:40], field)
        if found is None:
            continue
        i, name_used, _ = found
        lines[i] = f"**{name_used}:** {value}".rstrip()
        written[field] = value

    missing = [f for f in required if f not in written]
    if missing:
        return None

    # ⚠️ Follow a symlink before writing: `os.replace` would replace the LINK
    # with a plain file and leave the real document behind, still saying the old
    # thing. Somebody who linked their document somewhere meant it.
    if path.is_symlink():
        path = path.resolve()

    # A unique temporary name: a fixed one is two concurrent writes overwriting
    # each other's file, in the one place where that means a lost document.
    handle, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=".frontstep-", suffix=".tmp")
    os.close(handle)
    tmp = Path(tmp_name)
    try:
        before = path.stat()
        tmp.write_text(newline.join(lines), encoding="utf-8", newline="")
        os.chmod(tmp, stat.S_IMODE(before.st_mode))
        try:
            os.chown(tmp, before.st_uid, before.st_gid)
        except (PermissionError, AttributeError):
            pass
        os.replace(tmp, path)
    except OSError as e:
        tmp.unlink(missing_ok=True)
        raise WriteFailed(f"could not write {path.name}: {e}") from None
    return {"name": doc["name"], "language": language, "written": written}


def set_status(name: str, root_path: str, new_status: str,
               today: dt.date | None = None) -> dict | None:
    """Move the header's status to `new_status`, and its date along with it.
    None if the project does not exist or has no status line to change.

    There is no separate "closed" field: the machine-readable switch is the
    status the dashboard already reads — two fields would mean two truths.
    """
    # Tolerant on the way in, like the rest of the parser: a caller may pass
    # `done`, `concluso` or `closed`. What is NOT accepted is a status that does
    # not exist, and "undeclared", which is a diagnosis made by the dashboard
    # and not something one writes in a document.
    new_status = _normalize_status(new_status)
    if new_status not in STATUS_ORDER or new_status == UNDECLARED:
        return None

    day = (today or dt.date.today()).isoformat()
    done = _apply_to_header(
        name, root_path,
        lambda language: {"status": STATUS_BY_LANGUAGE[new_status][language],
                          "updated": day},
        # No status line to change means the document does not declare one, and
        # it refuses rather than inventing a header — that is the job of whoever
        # keeps that project. `updated` is not required: a header can be missing
        # it, and that is no reason not to move the status.
        required=("status",),
    )
    if done is None:
        return None
    # The status handed back is the CANONICAL one, not the way it was written to
    # the file: the page reads this, and the page thinks in one language.
    return {"name": done["name"], "status": new_status, "updated": day}


def set_next_step(name: str, root_path: str, text: str,
                  today: dt.date | None = None) -> dict | None:
    """Write the header's `Next step` line. None if there is no such line.

    The THIRD place this app writes inside somebody else's file, and it shares
    every defence with the other two: `_apply_to_header` above is the whole
    implementation, on purpose.

    Two decisions worth stating, because neither is obvious:

      * writing the next step MOVES `Updated` as well. In the end-of-session
        ritual they are one gesture, and a next step declared under last month's
        date claims the work moved when it did not;
      * there is NO length cap. Line breaks are folded away — the parser reads
        the field with a single-line regex, so a break would cut the value short
        — and nothing else is touched. A maximum here would be a style guideline
        dressed up as a constraint; the convention already asks for one
        imperative line, and asking is what a convention does.

    Refusing when the line is absent is the same rule as "Close": a command
    whose only possible outcome is an error is worse than no command, so the
    page does not show it either (`Project.has_next_step`).
    """
    text = " ".join((text or "").split())
    day = (today or dt.date.today()).isoformat()
    done = _apply_to_header(
        name, root_path,
        lambda language: {"next_step": text, "updated": day},
        required=("next_step",),
    )
    if done is None:
        return None
    return {"name": done["name"], "next_step": text, "updated": day}


# The scheme every VS Code family editor registers when it is installed —
# VS Code, VSCodium, Cursor and the rest answer to it. Chosen for "Open in
# editor" because it needs NOTHING of ours installed and works the same on
# Windows, macOS and Linux, unlike the `frontstep://` handler in contrib/,
# which is one machine's arrangement and has to be registered by hand.
def _remote_url(folder: Path) -> str:
    """The origin remote's URL, stripped of any credentials inside it.

    `.git/config` is read directly instead of running git: no subprocess, and a
    token that ended up inside a remote never passes through a command line.
    """
    cfg = folder / ".git" / "config"
    if not cfg.is_file():
        return ""
    parser = configparser.ConfigParser(strict=False)
    try:
        parser.read(cfg, encoding="utf-8")
    except (configparser.Error, OSError, UnicodeDecodeError):
        return ""
    for section in parser.sections():
        if section.replace('"', "").strip() == "remote origin":
            url = parser[section].get("url", "").strip()
            if not url:
                return ""
            url = re.sub(r"://[^/@]*@", "://", url)      # via user:token@
            return re.sub(r"\.git$", "", url)
    return ""


def _title_from_text(lines: list[str], fallback: str) -> str:
    for line in lines:
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


# Sections that answer "what is this". If a document has one, its first sentence
# is a better description than any line picked at random.
RE_ABOUT_SECTION = re.compile(
    r"^#{2,4}\s*\d*\.?\s*(what\s+(is|this|it)|about|purpose|summary|overview|"
    r"goal|objective|in\s+short|"
    r"cos'?\s*[eè]|cosa\s|obiettiv|scopo|panoramica|sintesi|introduzione)",
    re.IGNORECASE,
)
# A header field line, or a line of a key-value list: "**Status:** active",
# "**Date**: 2026-03-11". Not prose — data already shown elsewhere.
RE_FIELD_LINE = re.compile(r"^\*\*[^*]+\*\*\s*:|^\*\*[^*]+:\*\*")
# Lines that are not prose: headings, lists, tables, quotes, code, HTML.
RE_NOT_PROSE = re.compile(r"^(#|[-*+>|]|\d+[.)]\s|```|~~~|---|===|!\[|<)")
# A paragraph talking about the DOCUMENT rather than the project: the date of
# the last update is already on the card, and says nothing as a description.
RE_DOC_META = re.compile(
    r"^\**\s*(last\s+updated?|updated?\s+on|status\s+as\s+of|working\s+directory|"
    r"ultimo\s+aggiornament|data\s+ultimo|aggiornato\s+al|stato\s+al\b)",
    re.IGNORECASE,
)
# A derived description occupies the same space as a declared one: a subtitle,
# not a summary. The convention caps at 140; here it is a touch wider, because
# we are cutting someone else's sentence and the end of it is worth those 10.
MAX_DESCRIPTION = 150


def _is_prose(line: str) -> bool:
    text = line.strip()
    if len(text) < 25:                    # "**v5.0** (05/2026)" describes nothing
        return False
    return not (RE_NOT_PROSE.match(text) or RE_FIELD_LINE.match(text))


def _without_meta(paragraph: str) -> str:
    """Drop the sentences that talk about the document, not the project.

    This works on SENTENCES and not on whole paragraphs: "Status as of
    2026-06-18. Goal: review of the 2025 IT spend" is half meta and half the
    best description the document has — throwing all of it away is worse.
    """
    sentences = re.split(r"(?<=\.)\s+", paragraph)
    return " ".join(s for s in sentences if not RE_DOC_META.match(s.strip())).strip()


def _shorten(text: str, limit: int = MAX_DESCRIPTION) -> str:
    """Cut at the end of a sentence if one fits, otherwise at a word boundary."""
    # A trailing colon introduces a list that will never be seen here: as part
    # of a description it is left dangling.
    text = re.sub(r"\s+", " ", text).strip().rstrip(":")
    if len(text) <= limit:
        return text
    # A whole shorter sentence beats a line cut mid-word. The floor only serves
    # to discard stumps ("Done." as a description).
    stop = text.rfind(". ", 0, limit)
    if stop > limit * 0.25:
        return text[:stop + 1]
    return text[:text.rfind(" ", 0, limit)].rstrip(" ,;:") + "…"


def derived_description(lines: list[str]) -> str:
    """One line saying what the project is about, taken from its document.

    No new field to maintain: the description is not written, it is derived —
    like everything else on the page. The first sentence of an
    "About/Goal/Overview" section is preferred; failing that, the first prose in
    the body. If the document has no prose at all (only tables and lists) this
    returns "".

    It reasons in PARAGRAPHS, not lines: where text wraps by itself, taking a
    single line produces descriptions that start halfway through a clause.
    """
    first_prose = ""
    in_code = False
    skip_block = False                     # a list/table/quote is running
    under_about = False
    block: list[str] = []

    def evaluate(block: list[str]) -> str:
        """The paragraph with meta sentences removed, "" if it is not prose."""
        if not block:
            return ""
        text = _without_meta(" ".join(block))
        return text if _is_prose(text) else ""

    for line in list(lines) + [""]:        # the sentinel closes the last block
        text = line.strip()

        if text.startswith("```") or text.startswith("~~~"):
            in_code = not in_code
            block, skip_block = [], False
            continue
        if in_code:
            continue

        # A list glued to the paragraph, with no blank line between, CLOSES it:
        # its entries are not the description. And the lines that follow are not
        # a new paragraph, they are the continuation of that list.
        closes = (not text) or text.startswith("#") or RE_NOT_PROSE.match(text)

        if not closes:
            if not skip_block:
                block.append(text)
            continue

        candidate = evaluate(block)
        block = []
        if candidate:
            if under_about:                # the best source: stop here
                return _shorten(candidate)
            if not first_prose:
                first_prose = candidate    # keep it, but go on looking for better

        if not text:                       # only a blank line reopens prose
            skip_block = False
        elif text.startswith("#"):
            skip_block = False
            under_about = bool(RE_ABOUT_SECTION.match(text))
        else:
            skip_block = True              # we are inside a list or a table

    return _shorten(first_prose) if first_prose else ""


def read_project(folder: Path, root: Root) -> Project | None:
    """A project from its folder. None if there is no status file in it."""
    path = _find_status_file(folder)
    if path is None:
        return None

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None

    lines = text.split("\n")
    head = lines[:40]
    # The description is looked for across the document: an "About/Goal" section
    # sometimes sits at the bottom. The first 120 lines are enough and keep the
    # cost flat.
    body = lines[:120]

    raw_status = _read_field(head, "status")
    status = _normalize_status(raw_status)
    # `has_status` looks at the LINE, not the value: that is the one "Close"
    # rewrites. Without this the button showed up where it could not work, and
    # the only possible outcome was an error — as happened on documents that
    # have an `Updated` field but no `Status` one.
    has_status = _has_field(head, "status")
    # Same question for the next step, and for the same reason: the pencil on
    # the card is only shown where there is a line to rewrite. An EMPTY
    # `Next step:` counts — that is the normal state of a project waiting for
    # one, and it is exactly the line you want to fill in from the page.
    has_next_step = _has_field(head, "next_step")
    has_header = bool(has_status or _read_field(head, "updated"))

    # A declared field always wins: deriving from the text is the safety net for
    # documents that do not have that field yet.
    declared = _read_field(head, "description")

    app_name = _read_field(head, "app")
    prod = _read_field(head, "prod")
    in_production = bool(prod) and prod.strip().lower() not in PROD_NEGATIONS
    tags = project_tags(head, root.tags, in_production)

    try:
        mtime = dt.date.fromtimestamp(path.stat().st_mtime)
    except OSError:
        mtime = None

    return Project(
        name=folder.name,
        status=status or UNDECLARED,
        title=_title_from_text(head, folder.name),
        description=declared or derived_description(body),
        description_derived=not declared,
        folder=folder.name,
        root=root.key,
        prefix=root.prefix,
        host_folder=host_join(root.host, folder.name),
        tags=tags,
        app_name=app_name,
        in_production=in_production,
        prod_note=prod if in_production else "",
        updated=_parse_date(_read_field(head, "updated")),
        next_step=_read_field(head, "next_step"),
        waiting_for=_read_field(head, "waiting_for"),
        status_file=host_join(root.host, folder.name, path.name),
        status_filename=path.name,
        mtime=mtime,
        remote_url=_remote_url(folder),
        has_status_file=True,
        has_header=has_header,
        has_status=has_status,
        has_next_step=has_next_step,
        canonical_casing=path.name == CANONICAL_NAME,
    )


def read_index(path: Path) -> dict[str, dict]:
    """Projects declared in an external index file, keyed by folder.

    This is an optional source, off by default. It only serves the projects that
    do NOT have a status document: where the document exists, it is the truth.
    """
    entries: dict[str, dict] = {}
    if not path.is_file():
        return entries
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").split("\n")
    except OSError:
        return entries

    in_projects = False
    section_status = ACTIVE
    for line in lines:
        if line.startswith("## "):
            lowered = line.lower()
            in_projects = "project" in lowered or "progetti" in lowered
            # "## Projects — paused" sets the default for the lines that follow
            section_status = _normalize_status(line.split("—")[-1]) or ACTIVE
            continue
        if not in_projects:
            continue
        m = RE_INDEX_LINE.match(line.strip())
        if not m:
            continue
        desc = m.group("desc")
        reference = RE_REFERENCE.search(desc) or RE_REFERENCE.search(line)
        if not reference:
            continue

        # The last segment: the prefix is wherever that person keeps things.
        referenced = reference.group(1).rsplit("/", 1)[-1]
        title = m.group("title").strip()
        if RE_EXTENSION.search(referenced):
            # Not a folder but a file: the project is the one in the title, not
            # a project called "PIANO.md".
            name, folder = title, ""
        else:
            name, folder = referenced, referenced

        entries[name] = {
            "status": _normalize_status(m.group("status")) or section_status,
            "title": title,
            "folder": folder,
            "index_file": m.group("file").strip(),
            "note": desc.strip(),
        }
    return entries


def scan(roots: list[Root], index_file: str) -> list[Project]:
    """Every project under every root, already sorted for the page.

    A root that does not exist on disk is not an error: it is skipped. That way
    turning one off — or mounting only one inside a container — does not require
    touching the code.
    """
    projects: list[Project] = []
    # One root can contain another (`~/projects` sits inside the home folder):
    # the folder of a root is not a project of the other one, or it would show
    # up twice under two different addresses.
    # Device and inode are compared, not paths: inside a container the same
    # folder can be mounted twice under two different names, and as strings
    # those look nothing alike.
    other_roots = set()
    for r in roots:
        try:
            st = os.stat(r.folder)
            other_roots.add((st.st_dev, st.st_ino))
        except OSError:
            continue

    for root in roots:
        base = Path(root.folder)
        if not base.is_dir():
            continue
        for folder in sorted(base.iterdir(), key=lambda p: p.name.lower()):
            if not folder.is_dir() or folder.name.startswith("."):
                continue
            try:
                st = folder.stat()
            except OSError:
                continue
            if (st.st_dev, st.st_ino) in other_roots:
                continue
            project = read_project(folder, root)
            if project is not None:
                projects.append(project)

    # Projects that only live in the external index: cards without a status
    # document. The index refers to one root, so its projects belong to the
    # first one — and only those that do not already have a file there.
    index_root = roots[0] if roots else None
    if index_root is not None:
        seen = {p.name for p in projects if p.root == index_root.key}
        base = Path(index_root.folder)
        for name, entry in read_index(Path(index_file)).items():
            if name in seen:
                continue
            folder = base / entry["folder"] if entry["folder"] else None
            projects.append(Project(
                name=name,
                status=entry["status"],
                title=entry["title"],
                # With no status document there is nothing to derive from: the
                # index line is the only description that exists.
                description=entry["note"],
                description_derived=True,
                folder=entry["folder"],
                root=index_root.key,
                prefix=index_root.prefix,
                host_folder=(host_join(index_root.host, entry["folder"])
                             if entry["folder"] else ""),
                tags=index_root.tags,
                remote_url=_remote_url(folder) if folder and folder.is_dir() else "",
                has_status_file=False,
                index_note=entry["note"],
                index_file=entry["index_file"],
            ))

    # Within each status, the most recently worked on first: you scroll the page
    # starting from where you left off. Projects with no date at all go last.
    projects.sort(key=lambda p: (p.section_index,
                                 p.days_silent if p.days_silent is not None else 10 ** 6,
                                 p.name.lower(), p.root))
    return projects


def fingerprint(roots: list[Root], index_file: str) -> str:
    """A string that changes if and only if the files the page derives from
    change: which status files exist, when they were touched, how big they are.

    This is what the self-refresh runs on: the page compares it with its own and
    reloads only when the two differ. Reloading on a timer would cost the server
    the same but would interrupt reading for nothing — almost always nothing has
    changed.

    It costs one `stat` per project, not a read: no document is opened here, we
    only look at whether they are the same ones as before.
    """
    parts: list[str] = []
    for root in roots:
        base = Path(root.folder)
        if not base.is_dir():
            continue
        for folder in sorted(base.iterdir(), key=lambda p: p.name.lower()):
            if not folder.is_dir() or folder.name.startswith("."):
                continue
            path = _find_status_file(folder)
            if path is None:
                continue
            try:
                st = path.stat()
            except OSError:
                continue
            parts.append(f"{root.key}/{folder.name}/{path.name}"
                         f":{st.st_mtime_ns}:{st.st_size}")
    try:
        index = Path(index_file).stat()
        parts.append(f"index:{index.st_mtime_ns}:{index.st_size}")
    except OSError:
        pass
    return hashlib.sha1("\n".join(parts).encode("utf-8")).hexdigest()[:16]


# How many colours the tag palette has. Not a magic number: it is how many can
# actually be told apart at a glance on a small card. More colours only get you
# two different tags that look the same.
#
# ⚠️ SEVEN, and it used to be eight. The eighth was a red, and red is the one
# colour that means something on its own on a dashboard about state — a tag that
# happened to hash onto it made a perfectly healthy project look like an alarm.
# Nothing took its place, and that was measured rather than settled by taste:
# with the red gone the widest gap left in the palette is between brass (52°) and
# green (142°), and every colour that fits there lands about ΔE 24 from its
# nearest neighbour in the LIGHT theme, where all eight are darkened. The palette
# already has pairs that close, and adding another on purpose is how a colour
# stops distinguishing anything.
TAG_COLORS = 7


def color_index(tag: str) -> int:
    """The colour this tag PREFERS, from its name alone.

    Deterministic across machines and processes — an sha1 rather than `hash()`,
    which Python randomises per process. It is a preference and not the final
    answer, because a name knows nothing about the other names on the page: see
    `assign_colors`.
    """
    if not tag:
        return 0
    return int(hashlib.sha1(tag.encode("utf-8")).hexdigest()[:8], 16) % TAG_COLORS


def assign_colors(tags: list[str]) -> dict[str, int]:
    """A colour for each tag, resolving collisions against the others.

    ⚠️ The hash alone collides — measured: `work`, `prod` and `client` all land
    on the same colour — and the band is the card's only strong colour channel,
    so a collision costs the whole distinction. The hash chooses, the first tag
    to ask keeps its choice, the next slides on. `tags` arrives ordered by
    frequency, so the common ones keep the colour their name asks for.

    The trade: a tag's colour depends on the others, so adding one can shift
    another. Past `TAG_COLORS` tags every colour is taken and two will look
    alike — arithmetic, not a decision.
    """
    chosen: dict[str, int] = {}
    taken: set[int] = set()
    for tag in tags:
        if tag in chosen:
            continue
        want = color_index(tag)
        if want in taken:
            free = [c for c in range(TAG_COLORS) if c not in taken]
            want = free[0] if free else want
        chosen[tag] = want
        taken.add(want)
    return chosen


def count_tags(projects: list[Project]) -> list[tuple[str, int]]:
    """(tag, how many) ordered by frequency, then alphabetically on a tie.

    This is how the page knows which filters exist. Frequency order, because the
    filter bar shows the tags that actually earn the room first: a tag on one
    single project does not deserve the place of one describing forty.

    A tag carried by EVERY project separates nothing on its own: it is here all
    the same, since combined with the others it stays a legitimate filter, but
    the page puts it last — that is a judgement of the UI, not of this function.
    """
    counts: dict[str, int] = {}
    for project in projects:
        for tag in project.tags:
            counts[tag] = counts.get(tag, 0) + 1
    return sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))


def group_into_sections(projects: list[Project]) -> list[tuple[str, str, str, list[Project]]]:
    """The sections of the page: (key, label, status of the dot, members).

    Members arrive already sorted from `scan` and their order is not touched
    here: inside "Open", active and waiting stay mixed by recency.
    """
    sections = []
    for key, label, statuses in SECTIONS:
        members = [p for p in projects if p.status in statuses]
        if members:
            sections.append((key, label, statuses[0], members))
    return sections


# Ticks on the axis: values that can be read, not fractions of the maximum.
GRID_DAYS = [7, 30, 90, 180, 365]


def silence_line(projects: list[Project], stale_days: int = 7) -> dict:
    """Where each project sits on an axis running from the most silent to today.

    This is the view no single status document can give: where recent work
    gathers, and how long the tail that says nothing has grown.

    **Logarithmic, not linear.** On a linear scale one project untouched for
    five months squashes everything else into the last 5% of the axis, and the
    page stops answering the question it exists for. A logarithm is the normal
    scale for elapsed time: it tells 2 days from 20, and compresses the
    difference between 150 and 170, which changes no decision.

    **Open projects only.** The silence of a closed or shelved project is not a
    signal: those are not quiet, they are stopped by a decision already taken,
    and "silent for 370 days" on a paused project asks nothing of anybody.
    Keeping them stretched the axis past a year and pushed the live projects
    against the right edge — and those are the only thing this line has to show.
    """
    dated = [p for p in projects
             if p.days_silent is not None and p.status in OPEN_STATUSES]
    if not dated:
        return {"ticks": [], "grid": [], "max_days": 0}

    max_days = max(p.days_silent for p in dated) or 1
    scale = math.log1p(max_days)

    def position(days: int) -> float:
        """0% = the most silent project (left), 100% = today (right)."""
        return round(100 - (math.log1p(days) / scale * 100), 2)

    return {
        "ticks": [
            {"name": p.name, "ident": p.ident, "status": p.status,
             "tags": p.tags, "days": p.days_silent,
             "left": position(p.days_silent)}
            for p in dated
        ],
        # The threshold is already marked by the dashed edge of its zone: only
        # the OTHER reference values go here, not a duplicate of that one.
        "grid": [
            {"days": g, "left": position(g)}
            for g in GRID_DAYS if g < max_days and g != stale_days
        ],
        "max_days": max_days,
        "threshold_at": position(stale_days),
    }


def _commit_date(repo: Path, sha: str) -> dt.date | None:
    """The commit's date, read from the object in `.git/objects`.

    Same choice as the rest of the signature: `.git` is read by hand, with no
    subprocess. The object is zlib-compressed and contains the line
    `committer Name <email> <epoch> <offset>`: the timestamp is the second-last
    field.

    Returns None when the object is **packed** (after a `git gc` loose objects
    disappear into a packfile, a format with an index and deltas: reading it by
    hand would be a whole parser for one line of footer). Better no date than a
    date taken from somewhere else and nearly right — the ref's mtime would say
    when the branch was updated, which after a clone or a reset is not when the
    commit was written.
    """
    # 40 = sha1, 64 = sha256: a repository on the newer hash must work the same.
    if len(sha) not in (40, 64):
        return None
    obj = repo / ".git" / "objects" / sha[:2] / sha[2:]
    if not obj.is_file():
        return None
    try:
        raw = zlib.decompress(obj.read_bytes())
    except (OSError, zlib.error):
        return None
    for line in raw.split(b"\n"):
        if line.startswith(b"committer "):
            fields = line.split()
            if len(fields) < 2:
                return None
            try:
                return dt.datetime.fromtimestamp(int(fields[-2])).date()
            except (ValueError, OverflowError, OSError):
                return None
        if not line:                                   # blank line = end of header
            break
    return None


def _current_commit(repo: Path) -> tuple[str, str]:
    """(branch, full sha) of the repository the app runs from. ("", "") if it is
    not a repository at all.

    The sha comes back WHOLE: it is the key that opens the object in
    `.git/objects` to read its date. Truncating it to seven is the signature's
    job, which is where how a thing is shown gets decided.

    `.git` is read by hand instead of running `git`: no subprocess, same as for
    the remote URL. A branch ref may live in a file of its own or packed into
    `packed-refs`, and both have to be looked at — after a `gc` only the second
    one exists.
    """
    head = repo / ".git" / "HEAD"
    if not head.is_file():
        return "", ""
    try:
        content = head.read_text(encoding="utf-8").strip()
    except OSError:
        return "", ""
    if not content.startswith("ref:"):
        return "", content                             # detached HEAD
    ref = content.split(" ", 1)[1].strip()
    branch = ref.rsplit("/", 1)[-1]

    direct = repo / ".git" / ref
    try:
        if direct.is_file():
            return branch, direct.read_text(encoding="utf-8").strip()
        packed = repo / ".git" / "packed-refs"
        if packed.is_file():
            for line in packed.read_text(encoding="utf-8").splitlines():
                if line.endswith(" " + ref):
                    return branch, line.split(" ", 1)[0]
    except OSError:
        pass
    return branch, ""


def signature() -> dict:
    """The line at the bottom of the page: who made it, version, repo, commit.

    The sha is shown at seven characters (enough to find it again) and the date
    is the commit's, not the deploy's: together they say which point of the work
    this page is running from. `commit_date` is None when the object is packed —
    the page then shows the sha alone.

    `author` and `mark` come first and are not optional: see AUTHOR above, and
    NOTICE, which names this line as the display it requires.
    """
    branch, sha = _current_commit(REPO_ROOT)
    return {"author": AUTHOR, "mark": AUTHOR_MARK, "url": PROJECT_URL,
            "version": VERSION, "repo": REPO_NAME, "branch": branch,
            "commit": sha[:7], "commit_date": _commit_date(REPO_ROOT, sha)}


# Roots and settings do not live here any more: they are data, and `config.py`
# reads them from a TOML file. No folder and no label is written in the code.


__all__ = [
    "WriteFailed",
    "Project", "Root",
    # statuses, canonical in English
    "ACTIVE", "WAITING", "PAUSED", "DONE", "UNDECLARED",
    "STATUS_ORDER", "LABELS", "SECTIONS", "STATUS_BY_LANGUAGE",
    # the header fields, in both languages
    "FIELDS", "LANGUAGES", "field_names", "field_name", "document_language",
    # tags
    "PROD_TAG", "TAG_COLORS", "normalize_tag", "project_tags", "count_tags",
    "color_index", "assign_colors",
    "VERSION", "signature", "scan", "group_into_sections", "document", "fingerprint",
    "silence_line", "read_project", "read_index",
    # the three writes into somebody else's file, and their shared trunk
    "create_project", "set_status", "set_next_step",
    "derived_description", "suggest_roots",
]
